typedef struct
{
  unsigned char symbol;
  char name[16];
  int  pos;  
} accent_struct;

accent_struct accents[]= {
  { '/',  "OXIA", 3 },         
  { '\\',  "VARIA", 3 },        
  { '=',  "PERISPOMENI", 3 },  
  { '~',  "PERISPOMENI", 3 },  
  { '[',  "DASIA", 2 },        
  { ']',  "PSILI", 2 },        
  { '"',  "DIALYTIKA", 2 },    
  { '|',  "YPOGEGRAMMENI", 4 },
  { '-',  "MACRON", 3 },       
  { '^',  "VRACHY", 3 }
};

typedef struct
{
  unsigned int index;
  bool shift;
  char name[16];
  char pneuma[16];
  char tonos[16];
  char ypo[16];
} ucs_struct;

ucs_struct ucs_array[] = {  /* 273 entries */ 
  { 0X386, 1, "ALPHA", "", "OXIA", "" },
  { 0X388, 1, "EPSILON", "", "OXIA", "" },
  { 0X389, 1, "ETA", "", "OXIA", "" },
  { 0X38A, 1, "IOTA", "", "OXIA", "" },
  { 0X38C, 1, "OMICRON", "", "OXIA", "" },
  { 0X38E, 1, "UPSILON", "", "OXIA", "" },
  { 0X38F, 1, "OMEGA", "", "OXIA", "" },
  { 0X390, 0, "IOTA", "DIALYTIKA", "OXIA", "" },
  { 0X391, 1, "ALPHA", "", "", "" },
  { 0X395, 1, "EPSILON", "", "", "" },
  { 0X397, 1, "ETA", "", "", "" },
  { 0X399, 1, "IOTA", "", "", "" },
  { 0X39F, 1, "OMICRON", "", "", "" },
  { 0X3A1, 1, "RHO", "", "", "" },
  { 0X3A5, 1, "UPSILON", "", "", "" },
  { 0X3A8, 1, "PSI", "", "", "" },
  { 0X3A9, 1, "OMEGA", "", "", "" },
  { 0X3AA, 1, "IOTA", "DIALYTIKA", "", "" },
  { 0X3AB, 1, "UPSILON", "DIALYTIKA", "", "" },
  { 0X3AC, 0, "ALPHA", "", "OXIA", "" },
  { 0X3AD, 0, "EPSILON", "", "OXIA", "" },
  { 0X3AE, 0, "ETA", "", "OXIA", "" },
  { 0X3AF, 0, "IOTA", "", "OXIA", "" },
  { 0X3B0, 0, "UPSILON", "DIALYTIKA", "OXIA", "" },
  { 0X3B1, 0, "ALPHA", "", "", "" },
  { 0X3B5, 0, "EPSILON", "", "", "" },
  { 0X3B7, 0, "ETA", "", "", "" },
  { 0X3B9, 0, "IOTA", "", "", "" },
  { 0X3BF, 0, "OMICRON", "", "", "" },
  { 0X3C1, 0, "RHO", "", "", "" },
  { 0X3C5, 0, "UPSILON", "", "", "" },
  { 0X3C8, 0, "PSI", "", "", "" },
  { 0X3C9, 0, "OMEGA", "", "", "" },
  { 0X3CA, 0, "IOTA", "DIALYTIKA", "", "" },
  { 0X3CB, 0, "UPSILON", "DIALYTIKA", "", "" },
  { 0X3CC, 0, "OMICRON", "", "OXIA", "" },
  { 0X3CD, 0, "UPSILON", "", "OXIA", "" },
  { 0X3CE, 0, "OMEGA", "", "OXIA", "" },
  { 0X1D68, 0, "RHO", "", "", "" },
  { 0X1F00, 0, "ALPHA", "PSILI", "", "" },
  { 0X1F01, 0, "ALPHA", "DASIA", "", "" },
  { 0X1F02, 0, "ALPHA", "PSILI", "VARIA", "" },
  { 0X1F03, 0, "ALPHA", "DASIA", "VARIA", "" },
  { 0X1F04, 0, "ALPHA", "PSILI", "OXIA", "" },
  { 0X1F05, 0, "ALPHA", "DASIA", "OXIA", "" },
  { 0X1F06, 0, "ALPHA", "PSILI", "PERISPOMENI", "" },
  { 0X1F07, 0, "ALPHA", "DASIA", "PERISPOMENI", "" },
  { 0X1F08, 1, "ALPHA", "PSILI", "", "" },
  { 0X1F09, 1, "ALPHA", "DASIA", "", "" },
  { 0X1F0A, 1, "ALPHA", "PSILI", "VARIA", "" },
  { 0X1F0B, 1, "ALPHA", "DASIA", "VARIA", "" },
  { 0X1F0C, 1, "ALPHA", "PSILI", "OXIA", "" },
  { 0X1F0D, 1, "ALPHA", "DASIA", "OXIA", "" },
  { 0X1F0E, 1, "ALPHA", "PSILI", "PERISPOMENI", "" },
  { 0X1F0F, 1, "ALPHA", "DASIA", "PERISPOMENI", "" },
  { 0X1F10, 0, "EPSILON", "PSILI", "", "" },
  { 0X1F11, 0, "EPSILON", "DASIA", "", "" },
  { 0X1F12, 0, "EPSILON", "PSILI", "VARIA", "" },
  { 0X1F13, 0, "EPSILON", "DASIA", "VARIA", "" },
  { 0X1F14, 0, "EPSILON", "PSILI", "OXIA", "" },
  { 0X1F15, 0, "EPSILON", "DASIA", "OXIA", "" },
  { 0X1F18, 1, "EPSILON", "PSILI", "", "" },
  { 0X1F19, 1, "EPSILON", "DASIA", "", "" },
  { 0X1F1A, 1, "EPSILON", "PSILI", "VARIA", "" },
  { 0X1F1B, 1, "EPSILON", "DASIA", "VARIA", "" },
  { 0X1F1C, 1, "EPSILON", "PSILI", "OXIA", "" },
  { 0X1F1D, 1, "EPSILON", "DASIA", "OXIA", "" },
  { 0X1F20, 0, "ETA", "PSILI", "", "" },
  { 0X1F21, 0, "ETA", "DASIA", "", "" },
  { 0X1F22, 0, "ETA", "PSILI", "VARIA", "" },
  { 0X1F23, 0, "ETA", "DASIA", "VARIA", "" },
  { 0X1F24, 0, "ETA", "PSILI", "OXIA", "" },
  { 0X1F25, 0, "ETA", "DASIA", "OXIA", "" },
  { 0X1F26, 0, "ETA", "PSILI", "PERISPOMENI", "" },
  { 0X1F27, 0, "ETA", "DASIA", "PERISPOMENI", "" },
  { 0X1F28, 1, "ETA", "PSILI", "", "" },
  { 0X1F29, 1, "ETA", "DASIA", "", "" },
  { 0X1F2A, 1, "ETA", "PSILI", "VARIA", "" },
  { 0X1F2B, 1, "ETA", "DASIA", "VARIA", "" },
  { 0X1F2C, 1, "ETA", "PSILI", "OXIA", "" },
  { 0X1F2D, 1, "ETA", "DASIA", "OXIA", "" },
  { 0X1F2E, 1, "ETA", "PSILI", "PERISPOMENI", "" },
  { 0X1F2F, 1, "ETA", "DASIA", "PERISPOMENI", "" },
  { 0X1F30, 0, "IOTA", "PSILI", "", "" },
  { 0X1F31, 0, "IOTA", "DASIA", "", "" },
  { 0X1F32, 0, "IOTA", "PSILI", "VARIA", "" },
  { 0X1F33, 0, "IOTA", "DASIA", "VARIA", "" },
  { 0X1F34, 0, "IOTA", "PSILI", "OXIA", "" },
  { 0X1F35, 0, "IOTA", "DASIA", "OXIA", "" },
  { 0X1F36, 0, "IOTA", "PSILI", "PERISPOMENI", "" },
  { 0X1F37, 0, "IOTA", "DASIA", "PERISPOMENI", "" },
  { 0X1F38, 1, "IOTA", "PSILI", "", "" },
  { 0X1F39, 1, "IOTA", "DASIA", "", "" },
  { 0X1F3A, 1, "IOTA", "PSILI", "VARIA", "" },
  { 0X1F3B, 1, "IOTA", "DASIA", "VARIA", "" },
  { 0X1F3C, 1, "IOTA", "PSILI", "OXIA", "" },
  { 0X1F3D, 1, "IOTA", "DASIA", "OXIA", "" },
  { 0X1F3E, 1, "IOTA", "PSILI", "PERISPOMENI", "" },
  { 0X1F3F, 1, "IOTA", "DASIA", "PERISPOMENI", "" },
  { 0X1F40, 0, "OMICRON", "PSILI", "", "" },
  { 0X1F41, 0, "OMICRON", "DASIA", "", "" },
  { 0X1F42, 0, "OMICRON", "PSILI", "VARIA", "" },
  { 0X1F43, 0, "OMICRON", "DASIA", "VARIA", "" },
  { 0X1F44, 0, "OMICRON", "PSILI", "OXIA", "" },
  { 0X1F45, 0, "OMICRON", "DASIA", "OXIA", "" },
  { 0X1F48, 1, "OMICRON", "PSILI", "", "" },
  { 0X1F49, 1, "OMICRON", "DASIA", "", "" },
  { 0X1F4A, 1, "OMICRON", "PSILI", "VARIA", "" },
  { 0X1F4B, 1, "OMICRON", "DASIA", "VARIA", "" },
  { 0X1F4C, 1, "OMICRON", "PSILI", "OXIA", "" },
  { 0X1F4D, 1, "OMICRON", "DASIA", "OXIA", "" },
  { 0X1F50, 0, "UPSILON", "PSILI", "", "" },
  { 0X1F51, 0, "UPSILON", "DASIA", "", "" },
  { 0X1F52, 0, "UPSILON", "PSILI", "VARIA", "" },
  { 0X1F53, 0, "UPSILON", "DASIA", "VARIA", "" },
  { 0X1F54, 0, "UPSILON", "PSILI", "OXIA", "" },
  { 0X1F55, 0, "UPSILON", "DASIA", "OXIA", "" },
  { 0X1F56, 0, "UPSILON", "PSILI", "PERISPOMENI", "" },
  { 0X1F57, 0, "UPSILON", "DASIA", "PERISPOMENI", "" },
  { 0X1F59, 1, "UPSILON", "DASIA", "", "" },
  { 0X1F5B, 1, "UPSILON", "DASIA", "VARIA", "" },
  { 0X1F5D, 1, "UPSILON", "DASIA", "OXIA", "" },
  { 0X1F5F, 1, "UPSILON", "DASIA", "PERISPOMENI", "" },
  { 0X1F60, 0, "OMEGA", "PSILI", "", "" },
  { 0X1F61, 0, "OMEGA", "DASIA", "", "" },
  { 0X1F62, 0, "OMEGA", "PSILI", "VARIA", "" },
  { 0X1F63, 0, "OMEGA", "DASIA", "VARIA", "" },
  { 0X1F64, 0, "OMEGA", "PSILI", "OXIA", "" },
  { 0X1F65, 0, "OMEGA", "DASIA", "OXIA", "" },
  { 0X1F66, 0, "OMEGA", "PSILI", "PERISPOMENI", "" },
  { 0X1F67, 0, "OMEGA", "DASIA", "PERISPOMENI", "" },
  { 0X1F68, 1, "OMEGA", "PSILI", "", "" },
  { 0X1F69, 1, "OMEGA", "DASIA", "", "" },
  { 0X1F6A, 1, "OMEGA", "PSILI", "VARIA", "" },
  { 0X1F6B, 1, "OMEGA", "DASIA", "VARIA", "" },
  { 0X1F6C, 1, "OMEGA", "PSILI", "OXIA", "" },
  { 0X1F6D, 1, "OMEGA", "DASIA", "OXIA", "" },
  { 0X1F6E, 1, "OMEGA", "PSILI", "PERISPOMENI", "" },
  { 0X1F6F, 1, "OMEGA", "DASIA", "PERISPOMENI", "" },
  { 0X1F70, 0, "ALPHA", "", "VARIA", "" },
  { 0X1F72, 0, "EPSILON", "", "VARIA", "" },
  { 0X1F74, 0, "ETA", "", "VARIA", "" },
  { 0X1F76, 0, "IOTA", "", "VARIA", "" },
  { 0X1F78, 0, "OMICRON", "", "VARIA", "" },
  { 0X1F7A, 0, "UPSILON", "", "VARIA", "" },
  { 0X1F7C, 0, "OMEGA", "", "VARIA", "" },
  { 0X1F80, 0, "ALPHA", "PSILI", "", "YPOGEGRAMMENI" },
  { 0X1F81, 0, "ALPHA", "DASIA", "", "YPOGEGRAMMENI" },
  { 0X1F82, 0, "ALPHA", "PSILI", "VARIA", "YPOGEGRAMMENI" },
  { 0X1F83, 0, "ALPHA", "DASIA", "VARIA", "YPOGEGRAMMENI" },
  { 0X1F84, 0, "ALPHA", "PSILI", "OXIA", "YPOGEGRAMMENI" },
  { 0X1F85, 0, "ALPHA", "DASIA", "OXIA", "YPOGEGRAMMENI" },
  { 0X1F86, 0, "ALPHA", "PSILI", "PERISPOMENI", "YPOGEGRAMMENI" },
  { 0X1F87, 0, "ALPHA", "DASIA", "PERISPOMENI", "YPOGEGRAMMENI" },
  { 0X1F88, 1, "ALPHA", "PSILI", "", "YPOGEGRAMMENI" },
  { 0X1F89, 1, "ALPHA", "DASIA", "", "YPOGEGRAMMENI" },
  { 0X1F8A, 1, "ALPHA", "PSILI", "VARIA", "YPOGEGRAMMENI" },
  { 0X1F8B, 1, "ALPHA", "DASIA", "VARIA", "YPOGEGRAMMENI" },
  { 0X1F8C, 1, "ALPHA", "PSILI", "OXIA", "YPOGEGRAMMENI" },
  { 0X1F8D, 1, "ALPHA", "DASIA", "OXIA", "YPOGEGRAMMENI" },
  { 0X1F8E, 1, "ALPHA", "PSILI", "PERISPOMENI", "YPOGEGRAMMENI" },
  { 0X1F8F, 1, "ALPHA", "DASIA", "PERISPOMENI", "YPOGEGRAMMENI" },
  { 0X1F90, 0, "ETA", "PSILI", "", "YPOGEGRAMMENI" },
  { 0X1F91, 0, "ETA", "DASIA", "", "YPOGEGRAMMENI" },
  { 0X1F92, 0, "ETA", "PSILI", "VARIA", "YPOGEGRAMMENI" },
  { 0X1F93, 0, "ETA", "DASIA", "VARIA", "YPOGEGRAMMENI" },
  { 0X1F94, 0, "ETA", "PSILI", "OXIA", "YPOGEGRAMMENI" },
  { 0X1F95, 0, "ETA", "DASIA", "OXIA", "YPOGEGRAMMENI" },
  { 0X1F96, 0, "ETA", "PSILI", "PERISPOMENI", "YPOGEGRAMMENI" },
  { 0X1F97, 0, "ETA", "DASIA", "PERISPOMENI", "YPOGEGRAMMENI" },
  { 0X1F98, 1, "ETA", "PSILI", "", "YPOGEGRAMMENI" },
  { 0X1F99, 1, "ETA", "DASIA", "", "YPOGEGRAMMENI" },
  { 0X1F9A, 1, "ETA", "PSILI", "VARIA", "YPOGEGRAMMENI" },
  { 0X1F9B, 1, "ETA", "DASIA", "VARIA", "YPOGEGRAMMENI" },
  { 0X1F9C, 1, "ETA", "PSILI", "OXIA", "YPOGEGRAMMENI" },
  { 0X1F9D, 1, "ETA", "DASIA", "OXIA", "YPOGEGRAMMENI" },
  { 0X1F9E, 1, "ETA", "PSILI", "PERISPOMENI", "YPOGEGRAMMENI" },
  { 0X1F9F, 1, "ETA", "DASIA", "PERISPOMENI", "YPOGEGRAMMENI" },
  { 0X1FA0, 0, "OMEGA", "PSILI", "", "YPOGEGRAMMENI" },
  { 0X1FA1, 0, "OMEGA", "DASIA", "", "YPOGEGRAMMENI" },
  { 0X1FA2, 0, "OMEGA", "PSILI", "VARIA", "YPOGEGRAMMENI" },
  { 0X1FA3, 0, "OMEGA", "DASIA", "VARIA", "YPOGEGRAMMENI" },
  { 0X1FA4, 0, "OMEGA", "PSILI", "OXIA", "YPOGEGRAMMENI" },
  { 0X1FA5, 0, "OMEGA", "DASIA", "OXIA", "YPOGEGRAMMENI" },
  { 0X1FA6, 0, "OMEGA", "PSILI", "PERISPOMENI", "YPOGEGRAMMENI" },
  { 0X1FA7, 0, "OMEGA", "DASIA", "PERISPOMENI", "YPOGEGRAMMENI" },
  { 0X1FA8, 1, "OMEGA", "PSILI", "", "YPOGEGRAMMENI" },
  { 0X1FA9, 1, "OMEGA", "DASIA", "", "YPOGEGRAMMENI" },
  { 0X1FAA, 1, "OMEGA", "PSILI", "VARIA", "YPOGEGRAMMENI" },
  { 0X1FAB, 1, "OMEGA", "DASIA", "VARIA", "YPOGEGRAMMENI" },
  { 0X1FAC, 1, "OMEGA", "PSILI", "OXIA", "YPOGEGRAMMENI" },
  { 0X1FAD, 1, "OMEGA", "DASIA", "OXIA", "YPOGEGRAMMENI" },
  { 0X1FAE, 1, "OMEGA", "PSILI", "PERISPOMENI", "YPOGEGRAMMENI" },
  { 0X1FAF, 1, "OMEGA", "DASIA", "PERISPOMENI", "YPOGEGRAMMENI" },
  { 0X1FB0, 0, "ALPHA", "", "VRACHY", "" },
  { 0X1FB1, 0, "ALPHA", "", "MACRON", "" },
  { 0X1FB2, 0, "ALPHA", "", "VARIA", "YPOGEGRAMMENI" },
  { 0X1FB3, 0, "ALPHA", "", "", "YPOGEGRAMMENI" },
  { 0X1FB4, 0, "ALPHA", "", "OXIA", "YPOGEGRAMMENI" },
  { 0X1FB6, 0, "ALPHA", "", "PERISPOMENI", "" },
  { 0X1FB7, 0, "ALPHA", "", "PERISPOMENI", "YPOGEGRAMMENI" },
  { 0X1FB8, 1, "ALPHA", "", "VRACHY", "" },
  { 0X1FB9, 1, "ALPHA", "", "MACRON", "" },
  { 0X1FBA, 1, "ALPHA", "", "VARIA", "" },
  { 0X1FBC, 1, "ALPHA", "", "", "YPOGEGRAMMENI" },
  { 0X1FC2, 0, "ETA", "", "VARIA", "YPOGEGRAMMENI" },
  { 0X1FC3, 0, "ETA", "", "", "YPOGEGRAMMENI" },
  { 0X1FC4, 0, "ETA", "", "OXIA", "YPOGEGRAMMENI" },
  { 0X1FC6, 0, "ETA", "", "PERISPOMENI", "" },
  { 0X1FC7, 0, "ETA", "", "PERISPOMENI", "YPOGEGRAMMENI" },
  { 0X1FC8, 1, "EPSILON", "", "VARIA", "" },
  { 0X1FCA, 1, "ETA", "", "VARIA", "" },
  { 0X1FCC, 1, "ETA", "", "", "YPOGEGRAMMENI" },
  { 0X1FD0, 0, "IOTA", "", "VRACHY", "" },
  { 0X1FD1, 0, "IOTA", "", "MACRON", "" },
  { 0X1FD2, 0, "IOTA", "DIALYTIKA", "VARIA", "" },
  { 0X1FD3, 0, "IOTA", "DIALYTIKA", "OXIA", "" },
  { 0X1FD6, 0, "IOTA", "", "PERISPOMENI", "" },
  { 0X1FD7, 0, "IOTA", "DIALYTIKA", "PERISPOMENI", "" },
  { 0X1FD8, 1, "IOTA", "", "VRACHY", "" },
  { 0X1FD9, 1, "IOTA", "", "MACRON", "" },
  { 0X1FDA, 1, "IOTA", "", "VARIA", "" },
  { 0X1FE0, 0, "UPSILON", "", "VRACHY", "" },
  { 0X1FE1, 0, "UPSILON", "", "MACRON", "" },
  { 0X1FE2, 0, "UPSILON", "DIALYTIKA", "VARIA", "" },
  { 0X1FE3, 0, "UPSILON", "DIALYTIKA", "OXIA", "" },
  { 0X1FE4, 0, "RHO", "PSILI", "", "" },
  { 0X1FE5, 0, "RHO", "DASIA", "", "" },
  { 0X1FE6, 0, "UPSILON", "", "PERISPOMENI", "" },
  { 0X1FE7, 0, "UPSILON", "DIALYTIKA", "PERISPOMENI", "" },
  { 0X1FE8, 1, "UPSILON", "", "VRACHY", "" },
  { 0X1FE9, 1, "UPSILON", "", "MACRON", "" },
  { 0X1FEA, 1, "UPSILON", "", "VARIA", "" },
  { 0X1FEC, 1, "RHO", "DASIA", "", "" },
  { 0X1FF2, 0, "OMEGA", "", "VARIA", "YPOGEGRAMMENI" },
  { 0X1FF3, 0, "OMEGA", "", "", "YPOGEGRAMMENI" },
  { 0X1FF4, 0, "OMEGA", "", "OXIA", "YPOGEGRAMMENI" },
  { 0X1FF6, 0, "OMEGA", "", "PERISPOMENI", "" },
  { 0X1FF7, 0, "OMEGA", "", "PERISPOMENI", "YPOGEGRAMMENI" },
  { 0X1FF8, 1, "OMICRON", "", "VARIA", "" },
  { 0X1FFA, 1, "OMEGA", "", "VARIA", "" },
  { 0X1FFC, 1, "OMEGA", "", "", "YPOGEGRAMMENI" },
  { 0X20, "", "", "", "", "" },
  { 0X37A, "", "", "", "", "YPOGEGRAMMENI" },
  { 0XFBE, "", "", "", "", "YPOGEGRAMMENI" },
  { 0X1FBF, "", "", "PSILI", "", "" },
  { 0X1FC0, "", "", "", "PERISPOMENI", "" },
  { 0X1FC1, "", "", "DIALYTIKA", "PERISPOMENI", "" },
  { 0X1FCD, "", "", "PSILI", "VARIA", "" },
  { 0X1FCE, "", "", "PSILI", "OXIA", "" },
  { 0X1FCF, "", "", "PSILI", "PERISPOMENI", "" },
  { 0X1FDD, "", "", "DASIA", "VARIA", "" },
  { 0X1FDE, "", "", "DASIA", "OXIA", "" },
  { 0X1FDF, "", "", "DASIA", "PERISPOMENI", "" },
  { 0X1FED, "", "", "DIALYTIKA", "VARIA", "" },
  { 0X1FEE, "", "", "DIALYTIKA", "OXIA", "" },
  { 0X1FEF, "", "", "", "VARIA", "" },
  { 0X1FFD, "", "", "", "OXIA", "" },
  { 0X1FFE, "", "", "DASIA", "", "" },
};
